version: '3.5'
services:
  etcd:
    image: bitnami/etcd:latest
    volumes:
      - ./data:/bitnami/etcd/data
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - 2379:2379
      - 2380:2380
